### ISSUE TITLE
Coding Style reporté sur des fichiers Gitignorés

### ISSUE THREAD

**Issue by leodubosclard** [vavarier/install-discord-action#6]
Monsieur @vavarier,

Je me permets de vous écrire afin de vous rapporter un problème découvert lors de mon utilisation de votre projet "Discord CI".

En effet, j'ai eu le malheur de voir que la norminette Coding Style passait sur les fichiers présents dans le .gitignore. Vous m'en voyez boulebersé.

Pour le confort des yeux et de l'utilisation de DiscordCI. Merci de regler ce problème au plus vite.

Cordialement,

Léo Dubosclard
1ère année (Promotion 2026)
EPITECH Lyon
leo.dubosclard@epitech.eu

![image](https://user-images.githubusercontent.com/47077683/157701088-8865e56f-9cf9-4257-838e-99d4a2eeb6a4.png)

**Comment by vanouri** [comment]
merci bien pour cette précision sache que dés a présent le probléme est résolue et les fichier gitignore ce seront plus push n hésite pas a discordci update pour corriger ce probléme
