### ISSUE TITLE
Gitignored files not ignored

### ISSUE THREAD

**Issue by Just1truc** [vavarier/install-discord-action#7]
Hi,

I've installed your program and when i tried it, the files that i've pushed and that had their names written in the .gitignore file weren't  ignored as expected causing the result to have many coding style error.
This is pretty problematic because the goal of your project is testing and the testing part does not even work properly, returning to the user errors that should not have been here in the first place.
Consequently, i had to address this issue to see it fixed asap.

Yours sincerely,
Duc Justin

**Comment by vanouri** [comment]
sorry for this issue it is fix now don't be afraid to use discordci update
